version: '3'
services:
  api:
    build:
      context: '.'
      dockerfile: 'Dockerfile.api'
    ports:
      - '8080:3000'
    depends_on:
      - 'add'
      - 'multiply'
  add:
    build:
      context: '.'
      dockerfile: 'Dockerfile.add'
  multiply:
    build:
      context: '.'
      dockerfile: 'Dockerfile.multiply'
