version: '3'
services:
  user:
    container_name: 'user'
    build:
      context: '.'
      dockerfile: 'Dockerfile.user'
    ports:
      - '3001:3000'
    depends_on:
      - 'session'
  session:
    container_name: 'session'
    build:
      context: '.'
      dockerfile: 'Dockerfile.session'
    ports:
      - '3000:3000'
